[2024-12-21T20:10:25.832+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-21T20:10:25.868+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulator_1.call_kpi_endpoint manual__2024-12-21T20:07:40.795280+00:00 [queued]>
[2024-12-21T20:10:25.896+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulator_1.call_kpi_endpoint manual__2024-12-21T20:07:40.795280+00:00 [queued]>
[2024-12-21T20:10:25.899+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 3
[2024-12-21T20:10:25.957+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): call_kpi_endpoint> on 2024-12-21 20:07:40.795280+00:00
[2024-12-21T20:10:25.970+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=192) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-21T20:10:25.973+0000] {standard_task_runner.py:72} INFO - Started process 194 to run task
[2024-12-21T20:10:25.975+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'simulator_1', 'call_kpi_endpoint', 'manual__2024-12-21T20:07:40.795280+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/simulator_1.py', '--cfg-path', '/tmp/tmpyilz5sv5']
[2024-12-21T20:10:25.978+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask call_kpi_endpoint
[2024-12-21T20:10:26.577+0000] {task_command.py:467} INFO - Running <TaskInstance: simulator_1.call_kpi_endpoint manual__2024-12-21T20:07:40.795280+00:00 [running]> on host 6c02c561556a
[2024-12-21T20:10:26.845+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulator_1' AIRFLOW_CTX_TASK_ID='call_kpi_endpoint' AIRFLOW_CTX_EXECUTION_DATE='2024-12-21T20:07:40.795280+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-21T20:07:40.795280+00:00'
[2024-12-21T20:10:26.847+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-21T20:10:26.848+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-21T20:10:26.849+0000] {logging_mixin.py:190} INFO - Current task name:call_kpi_endpoint state:running start_date:2024-12-21 20:10:25.869813+00:00
[2024-12-21T20:10:26.849+0000] {logging_mixin.py:190} INFO - Dag name:simulator_1 and current dag run status:running
[2024-12-21T20:10:26.850+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-21T20:10:27.105+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulator_1.py", line 11, in call_kpi_endpoint
    print(response.json())
          ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-12-21T20:10:27.166+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-21T20:10:27.168+0000] {logging_mixin.py:190} INFO - Task start:2024-12-21 20:10:25.869813+00:00 end:2024-12-21 20:10:27.164925+00:00 duration:1.295112
[2024-12-21T20:10:27.170+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): call_kpi_endpoint> dag:<DAG: simulator_1> dagrun:<DagRun simulator_1 @ 2024-12-21 20:07:40.795280+00:00: manual__2024-12-21T20:07:40.795280+00:00, state:running, queued_at: 2024-12-21 20:07:46.274686+00:00. externally triggered: True>
[2024-12-21T20:10:27.171+0000] {logging_mixin.py:190} INFO - Failure caused by Expecting value: line 1 column 1 (char 0)
[2024-12-21T20:10:27.173+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=simulator_1, task_id=call_kpi_endpoint, run_id=manual__2024-12-21T20:07:40.795280+00:00, execution_date=20241221T200740, start_date=20241221T201025, end_date=20241221T201027
[2024-12-21T20:10:27.224+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-21T20:10:27.225+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 48 for task call_kpi_endpoint (Expecting value: line 1 column 1 (char 0); 194)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulator_1.py", line 11, in call_kpi_endpoint
    print(response.json())
          ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-12-21T20:10:27.322+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-21T20:10:27.795+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-21T20:10:27.799+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
