[2024-12-20T23:22:22.773+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:22:22.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:22:22.784+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:22:22.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:22:22.851+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:22:22.837+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_2.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-22 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:22:22.854+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:22:22.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.161 seconds
[2024-12-20T23:22:53.784+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:22:53.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:22:53.814+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:22:53.812+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:22:53.873+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:22:53.862+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_2.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-22 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:22:53.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:22:53.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.173 seconds
[2024-12-20T23:23:24.999+0000] {processor.py:186} INFO - Started process (PID=204) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:23:25.093+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:23:25.100+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:23:25.099+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:23:25.778+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:23:25.741+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_2.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-22 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:23:25.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:23:25.928+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.954 seconds
[2024-12-20T23:23:59.319+0000] {processor.py:186} INFO - Started process (PID=263) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:23:59.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:23:59.338+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:23:59.337+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:23:59.382+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:23:59.367+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_2.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-22 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:23:59.390+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:23:59.463+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.160 seconds
[2024-12-20T23:25:04.270+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:25:04.284+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:25:04.295+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:25:04.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:25:04.384+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:25:04.363+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_2.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-22 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:25:04.387+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:25:04.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.262 seconds
[2024-12-20T23:25:37.038+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:25:37.040+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:25:37.046+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:25:37.045+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:25:37.096+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:25:37.088+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_2.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-22 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:25:37.098+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:25:37.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.114 seconds
[2024-12-20T23:26:07.642+0000] {processor.py:186} INFO - Started process (PID=424) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:26:07.644+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:26:07.652+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:26:07.651+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:26:07.704+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:26:07.691+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_2.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-22 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:26:07.708+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:26:07.786+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.161 seconds
[2024-12-20T23:26:38.272+0000] {processor.py:186} INFO - Started process (PID=488) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:26:38.279+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:26:38.295+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:26:38.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:26:38.389+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:26:38.347+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_2.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-22 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:26:38.406+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:26:38.809+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.584 seconds
[2024-12-20T23:27:09.133+0000] {processor.py:186} INFO - Started process (PID=548) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:27:09.147+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:27:09.155+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:27:09.154+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:27:09.269+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:27:09.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_2.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-22 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:27:09.272+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:27:14.654+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 5.541 seconds
[2024-12-20T23:27:53.566+0000] {processor.py:186} INFO - Started process (PID=621) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:27:53.715+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:27:53.746+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:27:53.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:27:54.089+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:27:54.078+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_2.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-22 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:27:54.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:27:56.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 3.448 seconds
[2024-12-20T23:28:28.106+0000] {processor.py:186} INFO - Started process (PID=680) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:28:28.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:28:28.136+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:28:28.135+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:28:28.343+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:28:28.313+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:28:28.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:28:28.430+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.361 seconds
[2024-12-20T23:29:07.003+0000] {processor.py:186} INFO - Started process (PID=743) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:29:07.007+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:29:07.014+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:29:07.013+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:29:07.050+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:29:07.046+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:29:07.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:29:08.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 1.490 seconds
[2024-12-20T23:29:38.881+0000] {processor.py:186} INFO - Started process (PID=808) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:29:38.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:29:38.981+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:29:38.981+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:29:41.624+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:29:39.018+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:29:41.643+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:29:41.742+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 2.877 seconds
[2024-12-20T23:30:12.234+0000] {processor.py:186} INFO - Started process (PID=873) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:30:12.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:30:12.344+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:30:12.343+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:30:12.394+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:30:12.385+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:30:12.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:30:12.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.233 seconds
[2024-12-20T23:30:43.251+0000] {processor.py:186} INFO - Started process (PID=931) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:30:43.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:30:43.260+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:30:43.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:30:43.311+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:30:43.300+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:30:43.313+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:30:43.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.127 seconds
[2024-12-20T23:31:14.393+0000] {processor.py:186} INFO - Started process (PID=996) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:31:14.396+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:31:14.401+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:31:14.400+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:31:14.787+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:31:14.781+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:31:14.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:31:14.840+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.119 seconds
[2024-12-20T23:31:45.326+0000] {processor.py:186} INFO - Started process (PID=1051) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:31:45.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:31:45.332+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:31:45.331+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:31:45.361+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:31:45.357+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:31:45.362+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:31:45.400+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.087 seconds
[2024-12-20T23:32:17.488+0000] {processor.py:186} INFO - Started process (PID=1116) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:32:17.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:32:17.506+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:32:17.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:32:17.618+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:32:17.604+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:32:17.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:32:17.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.215 seconds
[2024-12-20T23:32:48.290+0000] {processor.py:186} INFO - Started process (PID=1177) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:32:48.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:32:48.298+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:32:48.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:32:48.328+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:32:48.324+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:32:48.329+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:32:48.369+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.092 seconds
[2024-12-20T23:33:19.485+0000] {processor.py:186} INFO - Started process (PID=1240) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:33:19.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:33:19.493+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:33:19.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:33:19.525+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:33:19.521+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:33:19.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:33:20.568+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 1.096 seconds
[2024-12-20T23:33:53.726+0000] {processor.py:186} INFO - Started process (PID=1300) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:33:53.728+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:33:53.734+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:33:53.733+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:33:53.765+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:33:53.760+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:33:53.766+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:33:54.024+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.310 seconds
[2024-12-20T23:34:25.705+0000] {processor.py:186} INFO - Started process (PID=1365) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:34:25.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:34:25.717+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:34:25.716+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:34:25.772+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:34:25.767+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:34:25.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:34:26.732+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 1.049 seconds
[2024-12-20T23:35:01.480+0000] {processor.py:186} INFO - Started process (PID=1430) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:35:01.486+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:35:01.504+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:35:01.502+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:35:01.605+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:35:01.593+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:35:01.608+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:35:01.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.296 seconds
[2024-12-20T23:35:33.177+0000] {processor.py:186} INFO - Started process (PID=1491) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:35:33.182+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:35:33.193+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:35:33.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:35:33.274+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:35:33.265+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:35:33.277+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:35:34.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.992 seconds
[2024-12-20T23:36:05.268+0000] {processor.py:186} INFO - Started process (PID=1557) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:36:05.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:36:05.276+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:36:05.275+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:36:05.309+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:36:05.305+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:36:05.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:36:05.852+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.598 seconds
[2024-12-20T23:36:37.063+0000] {processor.py:186} INFO - Started process (PID=1623) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:36:37.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:36:37.071+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:36:37.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:36:37.124+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:36:37.115+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:36:37.125+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:36:37.203+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.155 seconds
[2024-12-20T23:37:08.332+0000] {processor.py:186} INFO - Started process (PID=1685) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:37:08.336+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:37:08.343+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:37:08.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:37:08.394+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:37:08.388+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:37:08.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:37:08.450+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.139 seconds
[2024-12-20T23:37:40.074+0000] {processor.py:186} INFO - Started process (PID=1749) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:37:40.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:37:40.080+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:37:40.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:37:40.127+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:37:40.122+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:37:40.128+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:37:41.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 1.092 seconds
[2024-12-20T23:38:13.674+0000] {processor.py:186} INFO - Started process (PID=1815) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:38:13.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:38:13.682+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:38:13.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:38:13.732+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:38:13.725+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:38:13.734+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:38:13.792+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.137 seconds
[2024-12-20T23:38:44.283+0000] {processor.py:186} INFO - Started process (PID=1880) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:38:44.285+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:38:44.288+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:38:44.287+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:38:44.329+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:38:44.323+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:38:44.330+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:38:45.341+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 1.070 seconds
[2024-12-20T23:39:15.728+0000] {processor.py:186} INFO - Started process (PID=1946) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:39:15.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:39:15.777+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:39:15.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:39:15.815+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:39:15.811+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:39:15.816+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:39:16.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.298 seconds
[2024-12-20T23:39:48.901+0000] {processor.py:186} INFO - Started process (PID=2012) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:39:48.998+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:39:49.002+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:39:49.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:39:49.048+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:39:49.042+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:39:49.049+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:39:50.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 1.202 seconds
[2024-12-20T23:40:20.907+0000] {processor.py:186} INFO - Started process (PID=2077) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:40:20.910+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:40:20.914+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:40:20.913+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:40:20.991+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:40:20.971+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:40:20.996+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:40:21.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.259 seconds
[2024-12-20T23:40:52.211+0000] {processor.py:186} INFO - Started process (PID=2143) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:40:52.213+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:40:52.216+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:40:52.215+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:40:52.254+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:40:52.250+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:40:52.255+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:40:53.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.890 seconds
[2024-12-20T23:41:23.465+0000] {processor.py:186} INFO - Started process (PID=2208) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:41:23.467+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:41:23.470+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:41:23.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:41:23.523+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:41:23.507+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:41:23.524+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:41:24.528+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 1.079 seconds
[2024-12-20T23:41:55.018+0000] {processor.py:186} INFO - Started process (PID=2272) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:41:55.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:41:55.035+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:41:55.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:41:55.064+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:41:55.060+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:41:55.065+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:41:56.058+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 1.056 seconds
[2024-12-20T23:42:26.436+0000] {processor.py:186} INFO - Started process (PID=2339) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:42:26.438+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:42:26.442+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:42:26.442+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:42:26.476+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:42:26.471+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:42:26.477+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:42:26.518+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.097 seconds
[2024-12-20T23:42:57.969+0000] {processor.py:186} INFO - Started process (PID=2396) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:42:58.071+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:42:58.078+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:42:58.076+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:42:58.170+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:42:58.159+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:42:58.172+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:42:58.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.591 seconds
[2024-12-20T23:43:29.216+0000] {processor.py:186} INFO - Started process (PID=2462) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:43:29.227+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:43:29.231+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:43:29.230+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:43:29.271+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:43:29.265+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:43:29.272+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:43:29.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.118 seconds
[2024-12-20T23:44:02.502+0000] {processor.py:186} INFO - Started process (PID=2529) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:44:02.511+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:44:02.515+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:44:02.514+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:44:02.582+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:44:02.574+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:44:02.583+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:44:02.659+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.178 seconds
[2024-12-20T23:44:33.249+0000] {processor.py:186} INFO - Started process (PID=2595) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:44:33.252+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:44:33.255+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:44:33.254+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:44:33.292+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:44:33.285+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:44:33.293+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:44:34.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 1.094 seconds
[2024-12-20T23:45:05.413+0000] {processor.py:186} INFO - Started process (PID=2662) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:45:05.417+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:45:05.431+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:45:05.430+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:45:05.509+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:45:05.492+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:45:05.510+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:45:05.605+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.241 seconds
[2024-12-20T23:45:37.665+0000] {processor.py:186} INFO - Started process (PID=2729) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:45:37.668+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:45:37.672+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:45:37.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:45:37.719+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:45:37.713+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:45:37.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:45:37.776+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.130 seconds
[2024-12-20T23:46:10.588+0000] {processor.py:186} INFO - Started process (PID=2792) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:46:10.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:46:10.595+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:46:10.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:46:10.644+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:46:10.637+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:46:10.645+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:46:10.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.256 seconds
[2024-12-20T23:46:41.101+0000] {processor.py:186} INFO - Started process (PID=2858) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:46:41.114+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:46:41.118+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:46:41.117+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:46:41.157+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:46:41.152+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:46:41.158+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:46:41.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.126 seconds
[2024-12-20T23:47:12.247+0000] {processor.py:186} INFO - Started process (PID=2920) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:47:12.249+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:47:12.251+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:47:12.251+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:47:12.282+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:47:12.278+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:47:12.283+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:47:13.241+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 1.007 seconds
[2024-12-20T23:47:45.259+0000] {processor.py:186} INFO - Started process (PID=2972) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:47:45.262+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:47:45.265+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:47:45.264+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:47:45.603+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:47:45.597+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:47:45.604+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:47:45.646+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.407 seconds
[2024-12-20T23:48:18.296+0000] {processor.py:186} INFO - Started process (PID=3038) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:48:18.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:48:18.307+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:48:18.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:48:18.404+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:48:18.391+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:48:18.407+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:48:19.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 1.066 seconds
[2024-12-20T23:48:49.703+0000] {processor.py:186} INFO - Started process (PID=3104) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:48:49.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:48:49.715+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:48:49.713+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:48:49.852+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:48:49.839+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:48:49.854+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:48:50.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 1.122 seconds
[2024-12-20T23:49:26.029+0000] {processor.py:186} INFO - Started process (PID=3171) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:49:26.034+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:49:26.043+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:49:26.040+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:49:26.125+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:49:26.110+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:49:26.127+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:49:27.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 1.140 seconds
[2024-12-20T23:49:57.851+0000] {processor.py:186} INFO - Started process (PID=3233) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:49:57.853+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:49:57.857+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:49:57.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:49:57.891+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:49:57.887+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:49:57.892+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:49:58.469+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.631 seconds
[2024-12-20T23:50:28.951+0000] {processor.py:186} INFO - Started process (PID=3299) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:50:28.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:50:28.967+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:50:28.966+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:50:29.000+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:50:28.994+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:50:29.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:50:29.321+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.382 seconds
[2024-12-20T23:51:00.004+0000] {processor.py:186} INFO - Started process (PID=3363) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:51:00.006+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:51:00.009+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:51:00.009+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:51:00.050+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:51:00.044+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:51:00.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:51:01.039+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 1.047 seconds
[2024-12-20T23:51:35.433+0000] {processor.py:186} INFO - Started process (PID=3434) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:51:35.451+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:51:35.454+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:51:35.454+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:51:35.486+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:51:35.482+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:51:35.487+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:51:35.860+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.443 seconds
[2024-12-20T23:52:05.987+0000] {processor.py:186} INFO - Started process (PID=3500) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:52:05.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:52:05.994+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:52:05.992+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:52:06.039+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:52:06.032+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:52:06.041+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:52:06.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.124 seconds
[2024-12-20T23:52:39.408+0000] {processor.py:186} INFO - Started process (PID=3567) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:52:39.413+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:52:39.419+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:52:39.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:52:39.501+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:52:39.491+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:52:39.504+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:52:39.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.211 seconds
[2024-12-20T23:53:10.765+0000] {processor.py:186} INFO - Started process (PID=3633) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:53:10.768+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:53:10.772+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:53:10.771+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:53:10.824+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:53:10.818+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:53:10.826+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:53:10.883+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.133 seconds
[2024-12-20T23:53:41.800+0000] {processor.py:186} INFO - Started process (PID=3698) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:53:41.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:53:41.816+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:53:41.814+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:53:41.899+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:53:41.887+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:53:41.901+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:53:42.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.278 seconds
[2024-12-20T23:54:16.770+0000] {processor.py:186} INFO - Started process (PID=3763) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:54:16.774+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:54:16.778+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:54:16.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:54:16.846+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:54:16.836+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:54:16.847+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:54:16.910+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.156 seconds
[2024-12-20T23:56:55.847+0000] {processor.py:186} INFO - Started process (PID=74) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:56:55.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:56:55.866+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:56:55.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:56:55.934+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:56:55.918+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:56:55.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:56:55.996+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.187 seconds
[2024-12-20T23:57:26.654+0000] {processor.py:186} INFO - Started process (PID=141) to work on /opt/airflow/dags/simulator_2.py
[2024-12-20T23:57:26.657+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_2.py for tasks to queue
[2024-12-20T23:57:26.664+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:57:26.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:57:26.731+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:57:26.720+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:57:26.732+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_2.py
[2024-12-20T23:57:26.783+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_2.py took 0.144 seconds
