[2024-12-20T23:22:22.774+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:22:22.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:22:22.784+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:22:22.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:22:22.851+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:22:22.836+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_1.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-21 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:22:22.854+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:22:22.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.162 seconds
[2024-12-20T23:22:53.806+0000] {processor.py:186} INFO - Started process (PID=139) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:22:53.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:22:53.820+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:22:53.819+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:22:53.873+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:22:53.862+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_1.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-21 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:22:53.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:22:53.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.149 seconds
[2024-12-20T23:23:25.015+0000] {processor.py:186} INFO - Started process (PID=205) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:23:25.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:23:25.112+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:23:25.111+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:23:25.781+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:23:25.748+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_1.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-21 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:23:25.787+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:23:25.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.933 seconds
[2024-12-20T23:23:59.330+0000] {processor.py:186} INFO - Started process (PID=264) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:23:59.332+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:23:59.339+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:23:59.338+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:23:59.375+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:23:59.367+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_1.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-21 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:23:59.389+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:23:59.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.150 seconds
[2024-12-20T23:25:04.651+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:25:04.653+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:25:04.658+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:25:04.658+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:25:04.693+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:25:04.684+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_1.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-21 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:25:04.695+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:25:04.743+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.105 seconds
[2024-12-20T23:25:37.055+0000] {processor.py:186} INFO - Started process (PID=360) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:25:37.058+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:25:37.065+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:25:37.064+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:25:37.100+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:25:37.093+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_1.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-21 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:25:37.102+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:25:37.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.102 seconds
[2024-12-20T23:26:07.861+0000] {processor.py:186} INFO - Started process (PID=425) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:26:07.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:26:07.868+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:26:07.867+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:26:07.901+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:26:07.893+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_1.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-21 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:26:07.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:26:07.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.098 seconds
[2024-12-20T23:26:38.292+0000] {processor.py:186} INFO - Started process (PID=489) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:26:38.298+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:26:38.316+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:26:38.314+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:26:38.451+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:26:38.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_1.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-21 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:26:38.452+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:26:38.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.599 seconds
[2024-12-20T23:27:11.936+0000] {processor.py:186} INFO - Started process (PID=549) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:27:11.939+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:27:11.945+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:27:11.945+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:27:12.009+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:27:11.999+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_1.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-21 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:27:12.011+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:27:14.649+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 2.729 seconds
[2024-12-20T23:27:51.882+0000] {processor.py:186} INFO - Started process (PID=615) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:27:52.373+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:27:52.861+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:27:52.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:27:53.554+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:27:53.395+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/simulator_1.py", line 17, in <module>
    'start_date': datetime.strptime('2024-12-21 18:00:00+00:00', '%Y-%m-%d %H:%M:%S'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 655, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 437, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
[2024-12-20T23:27:53.557+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:27:56.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 5.142 seconds
[2024-12-20T23:28:28.112+0000] {processor.py:186} INFO - Started process (PID=681) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:28:28.134+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:28:28.150+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:28:28.145+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:28:28.345+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:28:28.314+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:28:28.348+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:28:28.437+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.360 seconds
[2024-12-20T23:29:07.886+0000] {processor.py:186} INFO - Started process (PID=744) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:29:08.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:29:08.504+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:29:08.502+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:29:08.771+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:29:08.752+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:29:08.774+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:29:08.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.971 seconds
[2024-12-20T23:29:42.228+0000] {processor.py:186} INFO - Started process (PID=809) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:29:42.238+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:29:42.246+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:29:42.244+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:29:42.825+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:29:42.818+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:29:42.831+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:29:42.910+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.174 seconds
[2024-12-20T23:30:13.870+0000] {processor.py:186} INFO - Started process (PID=874) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:30:13.929+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:30:13.936+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:30:13.935+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:30:14.004+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:30:13.997+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:30:14.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:30:14.059+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.208 seconds
[2024-12-20T23:30:45.508+0000] {processor.py:186} INFO - Started process (PID=939) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:30:45.511+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:30:45.517+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:30:45.516+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:30:45.553+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:30:45.548+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:30:45.554+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:30:45.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.099 seconds
[2024-12-20T23:31:15.956+0000] {processor.py:186} INFO - Started process (PID=1004) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:31:15.959+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:31:15.967+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:31:15.966+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:31:16.012+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:31:16.003+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:31:16.013+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:31:16.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.123 seconds
[2024-12-20T23:31:53.175+0000] {processor.py:186} INFO - Started process (PID=1065) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:31:53.180+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:31:53.193+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:31:53.191+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:31:53.287+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:31:53.276+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:31:53.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:31:53.648+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.506 seconds
[2024-12-20T23:32:24.752+0000] {processor.py:186} INFO - Started process (PID=1130) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:32:24.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:32:24.767+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:32:24.766+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:32:24.848+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:32:24.839+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:32:24.850+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:32:25.780+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 1.060 seconds
[2024-12-20T23:32:56.344+0000] {processor.py:186} INFO - Started process (PID=1194) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:32:56.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:32:56.356+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:32:56.355+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:32:56.421+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:32:56.413+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:32:56.423+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:32:57.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.979 seconds
[2024-12-20T23:33:30.941+0000] {processor.py:186} INFO - Started process (PID=1258) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:33:30.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:33:30.948+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:33:30.947+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:33:30.983+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:33:30.978+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:33:30.984+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:33:31.952+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 1.024 seconds
[2024-12-20T23:34:04.664+0000] {processor.py:186} INFO - Started process (PID=1320) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:34:04.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:34:04.671+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:34:04.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:34:04.708+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:34:04.704+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:34:04.709+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:34:05.119+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.468 seconds
[2024-12-20T23:34:36.893+0000] {processor.py:186} INFO - Started process (PID=1385) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:34:36.898+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:34:36.908+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:34:36.907+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:34:36.990+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:34:36.980+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:34:36.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:34:37.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.209 seconds
[2024-12-20T23:35:11.407+0000] {processor.py:186} INFO - Started process (PID=1450) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:35:11.502+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:35:11.505+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:35:11.505+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:35:11.533+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:35:11.530+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:35:11.534+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:35:11.689+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.290 seconds
[2024-12-20T23:35:44.929+0000] {processor.py:186} INFO - Started process (PID=1515) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:35:44.931+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:35:44.936+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:35:44.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:35:44.971+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:35:44.965+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:35:44.972+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:35:45.294+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.379 seconds
[2024-12-20T23:36:16.949+0000] {processor.py:186} INFO - Started process (PID=1580) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:36:16.952+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:36:16.958+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:36:16.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:36:17.004+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:36:16.999+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:36:17.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:36:17.044+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.112 seconds
[2024-12-20T23:36:47.617+0000] {processor.py:186} INFO - Started process (PID=1641) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:36:47.619+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:36:47.627+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:36:47.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:36:47.666+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:36:47.661+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:36:47.667+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:36:47.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.139 seconds
[2024-12-20T23:37:17.921+0000] {processor.py:186} INFO - Started process (PID=1707) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:37:17.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:37:17.940+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:37:17.938+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:37:18.021+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:37:18.011+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:37:18.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:37:18.086+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.193 seconds
[2024-12-20T23:37:52.432+0000] {processor.py:186} INFO - Started process (PID=1774) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:37:52.434+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:37:52.437+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:37:52.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:37:52.470+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:37:52.466+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:37:52.471+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:37:53.425+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 1.007 seconds
[2024-12-20T23:38:23.879+0000] {processor.py:186} INFO - Started process (PID=1841) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:38:23.881+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:38:23.883+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:38:23.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:38:23.915+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:38:23.911+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:38:23.917+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:38:23.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.124 seconds
[2024-12-20T23:38:55.617+0000] {processor.py:186} INFO - Started process (PID=1907) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:38:55.635+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:38:55.648+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:38:55.641+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:38:55.741+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:38:55.734+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:38:55.742+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:38:55.809+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.206 seconds
[2024-12-20T23:39:30.367+0000] {processor.py:186} INFO - Started process (PID=1969) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:39:30.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:39:30.856+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:39:30.855+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:39:30.902+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:39:30.895+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:39:30.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:39:30.956+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.121 seconds
[2024-12-20T23:40:02.034+0000] {processor.py:186} INFO - Started process (PID=2034) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:40:02.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:40:02.040+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:40:02.039+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:40:02.084+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:40:02.078+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:40:02.085+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:40:02.174+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.156 seconds
[2024-12-20T23:40:35.391+0000] {processor.py:186} INFO - Started process (PID=2100) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:40:35.393+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:40:35.396+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:40:35.395+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:40:35.433+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:40:35.429+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:40:35.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:40:35.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.135 seconds
[2024-12-20T23:41:07.402+0000] {processor.py:186} INFO - Started process (PID=2167) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:41:07.407+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:41:07.415+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:41:07.413+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:41:07.491+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:41:07.480+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:41:07.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:41:08.508+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 1.135 seconds
[2024-12-20T23:41:39.002+0000] {processor.py:186} INFO - Started process (PID=2234) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:41:39.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:41:39.038+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:41:39.036+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:41:39.222+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:41:39.171+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:41:39.226+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:41:39.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.322 seconds
[2024-12-20T23:42:10.209+0000] {processor.py:186} INFO - Started process (PID=2293) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:42:10.211+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:42:10.215+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:42:10.214+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:42:10.256+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:42:10.249+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:42:10.257+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:42:11.260+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 1.066 seconds
[2024-12-20T23:42:43.177+0000] {processor.py:186} INFO - Started process (PID=2359) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:42:43.179+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:42:43.182+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:42:43.181+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:42:43.214+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:42:43.209+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:42:43.215+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:42:43.253+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.094 seconds
[2024-12-20T23:43:13.487+0000] {processor.py:186} INFO - Started process (PID=2423) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:43:13.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:43:13.493+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:43:13.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:43:13.525+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:43:13.520+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:43:13.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:43:13.562+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.091 seconds
[2024-12-20T23:43:47.683+0000] {processor.py:186} INFO - Started process (PID=2496) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:43:47.762+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:43:47.768+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:43:47.767+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:43:47.803+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:43:47.798+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:43:47.804+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:43:47.850+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.212 seconds
[2024-12-20T23:44:18.643+0000] {processor.py:186} INFO - Started process (PID=2564) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:44:18.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:44:18.680+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:44:18.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:44:18.776+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:44:18.766+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:44:18.778+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:44:19.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 1.007 seconds
[2024-12-20T23:44:51.747+0000] {processor.py:186} INFO - Started process (PID=2632) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:44:51.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:44:51.752+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:44:51.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:44:51.788+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:44:51.781+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:44:51.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:44:51.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.097 seconds
[2024-12-20T23:45:21.942+0000] {processor.py:186} INFO - Started process (PID=2696) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:45:21.944+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:45:21.947+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:45:21.946+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:45:21.982+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:45:21.977+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:45:21.983+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:45:22.993+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 1.063 seconds
[2024-12-20T23:45:54.130+0000] {processor.py:186} INFO - Started process (PID=2763) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:45:54.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:45:54.143+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:45:54.141+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:45:54.236+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:45:54.221+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:45:54.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:45:55.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 1.025 seconds
[2024-12-20T23:46:27.374+0000] {processor.py:186} INFO - Started process (PID=2829) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:46:27.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:46:27.387+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:46:27.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:46:27.437+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:46:27.421+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:46:27.439+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:46:27.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.131 seconds
[2024-12-20T23:47:00.680+0000] {processor.py:186} INFO - Started process (PID=2889) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:47:00.690+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:47:00.702+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:47:00.700+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:47:00.781+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:47:00.772+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:47:00.782+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:47:00.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.184 seconds
[2024-12-20T23:47:33.442+0000] {processor.py:186} INFO - Started process (PID=2954) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:47:33.447+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:47:33.455+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:47:33.453+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:47:33.562+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:47:33.550+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:47:33.564+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:47:33.666+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.254 seconds
[2024-12-20T23:48:04.851+0000] {processor.py:186} INFO - Started process (PID=3020) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:48:04.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:48:04.861+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:48:04.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:48:04.937+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:48:04.926+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:48:04.939+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:48:05.904+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 1.080 seconds
[2024-12-20T23:48:36.899+0000] {processor.py:186} INFO - Started process (PID=3087) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:48:36.901+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:48:36.905+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:48:36.904+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:48:36.945+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:48:36.940+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:48:36.946+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:48:37.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.150 seconds
[2024-12-20T23:49:12.628+0000] {processor.py:186} INFO - Started process (PID=3150) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:49:12.631+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:49:12.634+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:49:12.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:49:12.673+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:49:12.667+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:49:12.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:49:13.441+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.829 seconds
[2024-12-20T23:49:44.311+0000] {processor.py:186} INFO - Started process (PID=3217) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:49:44.317+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:49:44.329+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:49:44.328+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:49:44.363+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:49:44.358+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:49:44.364+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:49:45.428+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 1.133 seconds
[2024-12-20T23:50:15.953+0000] {processor.py:186} INFO - Started process (PID=3282) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:50:15.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:50:15.959+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:50:15.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:50:16.006+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:50:16.000+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:50:16.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:50:16.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.321 seconds
[2024-12-20T23:50:49.135+0000] {processor.py:186} INFO - Started process (PID=3343) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:50:49.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:50:49.139+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:50:49.138+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:50:49.178+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:50:49.173+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:50:49.180+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:50:49.223+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.104 seconds
[2024-12-20T23:51:21.520+0000] {processor.py:186} INFO - Started process (PID=3402) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:51:21.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:51:21.619+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:51:21.618+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:51:21.660+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:51:21.654+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:51:21.661+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:51:22.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.842 seconds
[2024-12-20T23:51:53.446+0000] {processor.py:186} INFO - Started process (PID=3468) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:51:53.540+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:51:53.543+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:51:53.542+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:51:53.580+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:51:53.576+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:51:53.581+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:51:53.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.381 seconds
[2024-12-20T23:52:24.024+0000] {processor.py:186} INFO - Started process (PID=3534) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:52:24.038+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:52:24.042+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:52:24.041+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:52:24.084+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:52:24.077+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:52:24.086+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:52:24.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.123 seconds
[2024-12-20T23:52:56.008+0000] {processor.py:186} INFO - Started process (PID=3601) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:52:56.021+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:52:56.024+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:52:56.024+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:52:56.066+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:52:56.058+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:52:56.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:52:56.119+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.129 seconds
[2024-12-20T23:53:26.400+0000] {processor.py:186} INFO - Started process (PID=3664) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:53:26.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:53:26.405+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:53:26.404+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:53:26.436+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:53:26.429+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:53:26.437+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:53:26.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.092 seconds
[2024-12-20T23:53:57.051+0000] {processor.py:186} INFO - Started process (PID=3722) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:53:57.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:53:57.061+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:53:57.059+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:53:57.137+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:53:57.125+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:53:57.139+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:53:57.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.965 seconds
[2024-12-20T23:56:56.061+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:56:56.065+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:56:56.072+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:56:56.071+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:56:56.119+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:56:56.113+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:56:56.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:56:56.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.141 seconds
[2024-12-20T23:57:26.844+0000] {processor.py:186} INFO - Started process (PID=142) to work on /opt/airflow/dags/simulator_1.py
[2024-12-20T23:57:26.847+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/simulator_1.py for tasks to queue
[2024-12-20T23:57:26.855+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:57:26.854+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:57:26.904+0000] {logging_mixin.py:190} INFO - [2024-12-20T23:57:26.896+0000] {dagbag.py:484} ERROR - Failed to bag_dag: /opt/airflow/dags/simulator_1.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 102, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 271, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(
                                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 1032, in expand
    return cls._expand(expr_format, hash_id=hash_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/croniter/croniter.py", line 834, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5, 6 or 7 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 479, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 845, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/timetables/_cron.py", line 104, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5, 6 or 7 columns has to be specified for iterator expression.
[2024-12-20T23:57:26.905+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/simulator_1.py
[2024-12-20T23:57:26.965+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/simulator_1.py took 0.139 seconds
